name: test

on:
  push:
    branches:
      - main



permissions:
  contents: write
  pull-requests: write

# Each job requires the previous to run.
# They each use the reusable 'update-dep' workflow which takes as input the new version,
# and updates 
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Output pre-version
        run: |
          echo ${{github.event.release.tag_name}}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output post-version
        run: |
          echo ${{github.event.release.tag_name}}
          echo "Version: ${{ steps.semantic-release.outputs.version }}"
          echo "Version: ${{ steps.semantic-release.outputs.new-release-version }}"
          echo "Release Notes: ${{ steps.semantic-release.outputs.notes }}"
      - name: Get new version
        id: get-new-version
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # or your personal access token
        with:
          latest: true  
      - name: Export version
        run: |
          echo ${{steps.get-new-version.outputs.tag_name}}
          VERSION=${{steps.get-new-version.outputs.tag_name}}
  update-dev:
    uses: jonathanCS-org/called-repo/.github/workflows/update-ver.yml@main
    secrets: inherit
    with:
      version: $VERSION
      repo: caller-repo
  update-qual:
    needs: update-dev
    uses: jonathanCS-org/called-repo/.github/workflows/update-ver.yml@main
    secrets: inherit
    with:
      version: v1.4.0
      repo: caller-repo
  # update-acc:
  #   needs: update-qual
  #   uses: jonathanCS-org/called-repo/.github/workflows/reusable-test.yml@main
  #   secrets: inherit
  #   with:
  #     config-path: .github/labeler.yml
  # update-prod:
  #   needs: update-acc
  #   uses: jonathanCS-org/called-repo/.github/workflows/reusable-test.yml@main
  #   secrets: inherit
  #   with:
  #     config-path: .github/labeler.yml