name: test

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write

# Each job requires the previous to run.
# They each use the reusable 'update-dep' workflow which takes as input the new version,
# and updates 
jobs:
  update-dev:
    uses: jonathanCS-org/called-repo/.github/workflows/update-ver.yml@main
    secrets: inherit
    with:
      version: v1.4.0
      repo: caller-repo
  update-qual:
    needs: update-dev
    uses: jonathanCS-org/called-repo/.github/workflows/update-ver.yml@main
    secrets: inherit
    with:
      version: v1.4.0
      repo: caller-repo
  # update-acc:
  #   needs: update-qual
  #   uses: jonathanCS-org/called-repo/.github/workflows/reusable-test.yml@main
  #   secrets: inherit
  #   with:
  #     config-path: .github/labeler.yml
  # update-prod:
  #   needs: update-acc
  #   uses: jonathanCS-org/called-repo/.github/workflows/reusable-test.yml@main
  #   secrets: inherit
  #   with:
  #     config-path: .github/labeler.yml