name: test

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  call-workflow:
    uses: jonathanCS-org/called-repo/.github/workflows/reusable-test.yml@main
    secrets: inherit
    with:
      config-path: .github/labeler.yml
  call-workflow-2:
    needs: call-workflow
    uses: jonathanCS-org/called-repo/.github/workflows/reusable-test.yml@main
    secrets: inherit
    with:
      config-path: .github/labeler.yml